import { Inter } from 'next/font/google';
import './globals.css';
import ThemeProvider from '@/providers/ThemeProvider';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin-ext'] });

export const metadata = {
    title: 'Pro Minhaj',
    description: 'Generated by pro minhaj'
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
          <head>
        <meta name="cryptomus" content="e78d72a9" />
      </head>
            <body className={cn(inter.className, 'dark:bg-[#03060D] bg-[#FFFFFF]')}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='dark'
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
